BASE_TASK_CONFIG_PATH: "configs/tasks/nearTarget/train_nearTarget.yaml"
NUM_PROCESSES: 14
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
EXTRA_DEPTH: True

#### 8 GPU
NUM_UPDATES: 67142
LOG_INTERVAL: 50
CHECKPOINT_INTERVAL: 1342   # 90, 671 was 5, 1342


RL:
  PPO:
    # replace with path to checkpoint for passive pretraining
    pretrained_passive_separators_ckpt: "runs/passive_pretrain/new/data/best_ckpt_nonoverlapping_val.pth"

    use_location_in_policy: True

    use_predictedLocation_in_policy: True
    locationPredictor_encoderType: "resnet"
    locationPredictor_ckpt: "data/active_datasets/v1_old/train_731243episodes/regression_resnet_filtered_28oct_rectified_20_lr_1e-4_l1_factor1/best_val_ckpt_b.pth"
    # "data/active_datasets/v1_old/train_731243episodes/regression_resnet_filtered_28oct_rectified_20_lr_1e-4_l1_factor1/best_val_ckpt_b.pth"
    # locationPredictor_ckpt: "data/active_datasets/v1_old/train_731243episodes/regression_resnet_filtered_30oct_rectified_40_lr_1e-4_l1_factor1/best_val_ckpt.pth"

    ablate_vision: True

    sep_reward_wt: 1.0 
    geo_reward_wt: 1.0 # assign reward weightage here ## CHANGE DONE HERE

    hidden_size: 512

    clip_param: 0.1
    ppo_epoch: 4
    num_mini_batch: 1
    eps: 1.0e-5
    max_grad_norm: 0.5
    num_steps: 20

    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr_pol: 1.0e-4 
    lr_sep: 5.0e-3 

    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True

    reward_window_size: 50

    ### SEQ MEMORY
    TRANSFORMER_MEMORY:
        num_past_steps_refinement: 14

        memory_size: 19 
        input_size: 1024
        hidden_size: 1024
        num_layers: 2
        nhead: 8
        dropout: 0.0
        activation: 'relu'

        POSE_ENCODING:
            num_pose_attrs: 4
    
    use_ddppo: True
    ddppo_distrib_backend: "NCCL"
    short_rollout_threshold: 1.0  
    sync_frac: 0.6
   
