ENVIRONMENT:
  MAX_EPISODE_STEPS: 20
SIMULATOR:
  IS_GT_LOCATION_CORRECTLY_ORIENTED: True
  SCENE_DATASET: "mp3d"
  GRID_SIZE: 1.0
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  AUDIO:
    RIR_SAMPLING_RATE:  16000
    NORM_TYPE: "l2"
    GT_MONO_MAG_NORM: 1.2

    MONO_DIR: "data/audio_data/libriSpeech100Classes_MITMusic_ESC50/min20s_clips/train_preprocessed"

  TYPE: "HabitatSimAudioEnabled"
  ACTION_SPACE_CONFIG: "audio-separation"

TASK:
  TYPE: AAViDSS
  SENSORS: ["MIXED_BIN_AUDIO_MAG_SENSOR", "GT_BIN_COMPONENTS_SENSOR", "GT_MONO_COMPONENTS_SENSOR",
            "TARGET_CLASS_SENSOR", "POSE_SENSOR", "GT_DELTAX_DELTAY_SENSOR", "GT_GEODESIC_DISTANCE_SENSOR"] # , "GT_GEODESIC_DISTANCE_SENSOR"] ## CHANGE DONE HERE
  GOAL_SENSOR_UUID: mixed_bin_audio_mag
  MEASUREMENTS: []
  POSSIBLE_ACTIONS: ["MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]

DATASET:
  TYPE: "AAViDSS"
  SPLIT: "train_731243episodes"
  VERSION: 'v1'
  CONTENT_SCENES: ["*"]
  SCENES_DIR: "data/scene_datasets/mp3d"
  DATA_PATH: "data/active_datasets/{version}/{split}/{split}.json.gz"
  
